language: php

php:
  - 5.5

env:
  - DB=pgsql
  - SYMFONY_VERSION=2.6.*

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer install

script:
  - bin/phpunit -c app

notifications:
  email: boldtrn@gmail.com