language: php

php:
  - 5.5

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database jsonb_test;' -U postgres
  - composer install -n --no-interaction --prefer-source

script:
  - phpunit

notifications:
  email: boldtrn@gmail.com