language: php

php:
  - 5.5
  - 5.6

env:
  - DB=pgsql
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer install

script:
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/travis.xml $PHPUNIT_FLAGS
  - ENABLE_SECOND_LEVEL_CACHE=1 ./vendor/bin/phpunit -v -c tests/travis/travis.xml --exclude-group performance,non-cacheable,locking_functional
  - ./bin/phpunit -c app/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: boldtrn@gmail.com