language: php

php:
  - 5.5

env:
  - DB=pgsql
  - SYMFONY_VERSION=2.6.*

before_script:
  - composer install -n --no-interaction

script:
  - phpunit -c app

notifications:
  email: boldtrn@gmail.com