language: php

php:
  - 5.5

env:
  - DB=pgsql
  - SYMFONY_VERSION=2.6.*

before_script:
  - composer self-update
  - composer install -n --no-interaction

script:
  - bin/phpunit -c app -v --debug

notifications:
  email: boldtrn@gmail.com